### ISSUE TITLE
unable to install from git pull

### ISSUE THREAD

**Issue by mistergibson** [Hanmac/rwx#16]
To reproduce:

gem install ./rwx-0.0.1.1.dev.gem 
Building native extensions.  This could take a while...
ERROR:  Error installing ./rwx-0.0.1.1.dev.gem:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.0 extconf.rb
checking for HAVE_RB_DATA_TYPE_T_PARENT... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby2.0
	--with-rwx-dir
	--without-rwx-dir
	--with-rwx-include
	--without-rwx-include=${rwx-dir}/include
	--with-rwx-lib
	--without-rwx-lib=${rwx-dir}/
/usr/lib/ruby/2.0.0/mkmf.rb:1710:in `pkg_config': wrong number of arguments (2 for 1) (ArgumentError)
	from extconf.rb:25:in `<main>'

Gem files will remain installed in /var/lib/gems/2.0.0/gems/rwx-0.0.1.1.dev for inspection.
Results logged to /var/lib/gems/2.0.0/gems/rwx-0.0.1.1.dev/ext/gem_make.out

Note that I have the wxWidgets 3.0 headers and lib installed (Linux system)

**Comment by Hanmac** [comment]
Yeah the Gem was not updated a long time ago.
Please try to build it from trunk.

But I think the main Problem is the ruby version. Try to use a newer one like 2.1.

**Comment by mistergibson** [comment]
2.1 is not available yet in my distro -- how do I build from trunk?

**Comment by maathieu** [comment]
you'll also get plenty of problems with gcc mismatch and c++ errors ^^ I'll probably do a pull request for those!

**Comment by mbrethes** [comment]
I have made some modifications that enabled me to compile this on Debian Bullseye! Check t[he pull request here](https://github.com/Hanmac/rwx/pull/17).
